name: clmr 
channels:
  - pytorch
dependencies:
  - pip
  - pytorch
  - torchvision
  - pyyaml
  - pip:
    - essentia
    - imageio
    - matplotlib
    - pydot
    - python-dotenv
    - seaborn
    - tensorboard
    - torchaudio
    - torchvision
    - youtube-dl