name: clmr 
channels:
  - pytorch
dependencies:
  - pip
  - pytorch
  - torchvision
  - pyyaml
  - pip:
    - essentia
    - imageio
    - imblearn
    - matplotlib
    - opencv-python
    - pydot
    - python-dotenv
    - scikit-multilearn
    - seaborn
    - tensorboard
    - torchaudio
    - torchvision
    - tqdm
    - youtube-dl
