# train options
seed: 42 # sacred handles automatic seeding when passed in the config
batch_size: 128 # 64 for audio, 256 for images
num_workers: 16
start_epoch: 0
epochs: 10000

# task / dataset options
domain: "audio" # [audio,scores]
task: "tags" # [tags,chords,symbol]
dataset: "magnatagatune" # [audio: [billboard,fma,magnatagatune] vision: [deepscores,universal]]
data_input_dir: "datasets/audio" # [audio: [datasets/audio] vision: [datasets/vision]

# audio
audio_length: 20736 
sample_rate: 8000

normalize: True
projection_dim: 128
dropout: 0.5

# transformations
transforms_phase: 0.5
transforms_gain: 0.8
transforms_filters: 0.4

# model options
resnet: "resnet50"

# loss options
optimizer: "Adam" # [Adam, LARS]
weight_decay: 1.0e-6
temperature: 0.5 # (NOTE: 0.1 goes very fast) see appendix B.7.: Optimal temperature under different batch sizes

# mixed-precision training
fp16: False 
fp16_opt_level: "O2"


# magnatagatune
mtt_pons_eval: True
# use FULL dataset for pre-training, since segmented version are COROLLATED
# use normal dataset for lin. eval.
lin_eval: False
# mtt_processed_audio: "./datasets/audio/magnatagatune/processed_concat_8000"
mtt_processed_audio: "./datasets/audio/magnatagatune/processed_8000"
mtt_processed_annot: "./datasets/audio/magnatagatune/processed_annotations"
list_of_tags: "./datasets/audio/magnatagatune/50_tags.txt"
num_tags: 50


# reload options
reload: False
model_path: "logs/audio/magnatagatune/94" # set to the directory containing `checkpoint_##.tar` 
epoch_num: 230 # set to checkpoint number
# model_path: "logs/audio/magnatagatune/39" # set to the directory containing `checkpoint_##.tar` 
# epoch_num: 550 # set to checkpoint number


# logistic regression options
mlp: False 
perc_train_data: 1.0
logistic_batch_size: 64
logistic_epochs: 275
reload_logreg: False
logistic_lr: 0.0002
# logreg_model_path: "logs/audio/magnatagatune/41"
# logreg_epoch_num: 30 
# logreg_model_path: "logs/audio/magnatagatune/47"
# logreg_epoch_num: 27
logreg_model_path: "logs/audio/magnatagatune/54"
logreg_epoch_num: 50

## vision
image_height: 220
image_width: 120
image_channels: 1


universal_symbol_processed: "./datasets/vision/universal_symbol"
# image_height: 96
# image_width: 96
# image_channels: 3
